#server:
#  port: 8081
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb://mongo:27017/resource-db
server:
  port: 18081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/booksdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest